---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: ${{values.system}}-${{values.env}}-s3
  namespace: ${{values.system}}
  labels:
    backstage.io/kubernetes-id: ${{values.system}}
spec:
  forProvider:
    acl: private
    locationConstraint: us-east-1
    objectLockEnabledForBucket: false
  providerConfigRef:
    name: default


apiVersion: storage.gcp.crossplane.io/v1alpha3
kind: Bucket
metadata:
  name: ${{values.system}}-${{values.env}}-gcp
  labels:
    example: "true"
  annotations:
    # Note that this will be the actual bucket name so it has to be globally unique/available.
    crossplane.io/external-name: crossplane-example-bucket
spec:
  location: US
  storageClass: MULTI_REGIONAL
  providerConfigRef:
    name: gcp-provider
  deletionPolicy: Delete    